### ISSUE TITLE
Custom icons per "Creature"

### ISSUE THREAD

**Issue by autoOptions** [drakewill-CRL/Hypothesis#1]
Hello, first of all thank you for the source code, you've provided everything I need to get my own GeoLocation game up and running. Its been something i've been wanting to do for quite some time, and since I've been using solar2d since the early 2010s, This is the perfect beginning. 

I have everything server side already setup, complete with custom map tiles, and everything is working perfectly. 

I ran into a snag client side, when trying to provide custom icons per "Creature" that spawns on the map, since you are the original creator maybe you can provide some insight so I do not have to completely rewrite the code. 

I've seen your post in the solar2d discord, so let me know if contacting you here or through the discord is more convenient. 

Thank you!

**Comment by drakewill-CRL** [comment]
Hi! I'm very excited that you found my work and the server-side part went perfect for you.

The only hint I can provide for this, with the one detail that you want unique icons per creature, is that line 489 in CreatureCollectorScene.lua is where it draws the icon, using the file themables/creatureSpot.png. You'll want to change that string to whichever image you want to use instead. You may also need to add the baseDir parameter if you download those icons, since they won't be in the default resourcesFolder.

If you're looking to make each icon be the image for the creature, you probably want that line to look like:
`thisIcon = display.newImageRect(creaturesOnMap, v.imageName, shiftPixelsX, shiftPixelsY)`

The v in the loop at that point should be the creature data from defaultConfig.creatures, so if you want to add icons that aren't the full-sized image to use, you can add it to the creature's properties starting at line 63.

I hope this helps you!

**Comment by autoOptions** [comment]
Thank you! I knew it was probably something small I was just overlooking, everything is perfect now! I appreciate the quick response, I'm sure I will probably run into questions in the future, look forward to working through the issues again!
